package com.drpeng.ordercenter.persistence.mapper;

import com.drpeng.ordercenter.persistence.entity.CfgBusinessProcess;
import com.drpeng.ordercenter.persistence.entity.CfgBusinessProcessExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface CfgBusinessProcessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business_process
     *
     * @mbg.generated
     */
    long countByExample(CfgBusinessProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business_process
     *
     * @mbg.generated
     */
    int deleteByExample(CfgBusinessProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business_process
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer businessProcessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business_process
     *
     * @mbg.generated
     */
    int insert(CfgBusinessProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business_process
     *
     * @mbg.generated
     */
    int insertSelective(CfgBusinessProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business_process
     *
     * @mbg.generated
     */
    List<CfgBusinessProcess> selectByExampleWithRowbounds(CfgBusinessProcessExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business_process
     *
     * @mbg.generated
     */
    List<CfgBusinessProcess> selectByExample(CfgBusinessProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business_process
     *
     * @mbg.generated
     */
    CfgBusinessProcess selectByPrimaryKey(Integer businessProcessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business_process
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CfgBusinessProcess record, @Param("example") CfgBusinessProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business_process
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CfgBusinessProcess record, @Param("example") CfgBusinessProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business_process
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CfgBusinessProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business_process
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CfgBusinessProcess record);
}