package com.drpeng.ordercenter.persistence.mapper;

import com.drpeng.ordercenter.persistence.entity.CfgBusinessProcessMapping;
import com.drpeng.ordercenter.persistence.entity.CfgBusinessProcessMappingExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface CfgBusinessProcessMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business_process_mapping
     *
     * @mbg.generated
     */
    long countByExample(CfgBusinessProcessMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business_process_mapping
     *
     * @mbg.generated
     */
    int deleteByExample(CfgBusinessProcessMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business_process_mapping
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer mappingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business_process_mapping
     *
     * @mbg.generated
     */
    int insert(CfgBusinessProcessMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business_process_mapping
     *
     * @mbg.generated
     */
    int insertSelective(CfgBusinessProcessMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business_process_mapping
     *
     * @mbg.generated
     */
    List<CfgBusinessProcessMapping> selectByExampleWithRowbounds(CfgBusinessProcessMappingExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business_process_mapping
     *
     * @mbg.generated
     */
    List<CfgBusinessProcessMapping> selectByExample(CfgBusinessProcessMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business_process_mapping
     *
     * @mbg.generated
     */
    CfgBusinessProcessMapping selectByPrimaryKey(Integer mappingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business_process_mapping
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CfgBusinessProcessMapping record, @Param("example") CfgBusinessProcessMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business_process_mapping
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CfgBusinessProcessMapping record, @Param("example") CfgBusinessProcessMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business_process_mapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CfgBusinessProcessMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business_process_mapping
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CfgBusinessProcessMapping record);
}