package com.drpeng.ordercenter.persistence.mapper;

import com.drpeng.ordercenter.persistence.entity.CfgBusiness;
import com.drpeng.ordercenter.persistence.entity.CfgBusinessExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

@Mapper
public interface CfgBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business
     *
     * @mbggenerated
     */
    int countByExample(CfgBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business
     *
     * @mbggenerated
     */
    int deleteByExample(CfgBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer businessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business
     *
     * @mbggenerated
     */
    int insert(CfgBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business
     *
     * @mbggenerated
     */
    int insertSelective(CfgBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business
     *
     * @mbggenerated
     */
    List<CfgBusiness> selectByExampleWithRowbounds(CfgBusinessExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business
     *
     * @mbggenerated
     */
    List<CfgBusiness> selectByExample(CfgBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business
     *
     * @mbggenerated
     */
    CfgBusiness selectByPrimaryKey(Integer businessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CfgBusiness record, @Param("example") CfgBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CfgBusiness record, @Param("example") CfgBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CfgBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_business
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CfgBusiness record);
}