package com.drpeng.ordercenter.persistence.mapper;

import com.drpeng.ordercenter.persistence.entity.CfgExternalApi;
import com.drpeng.ordercenter.persistence.entity.CfgExternalApiExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface CfgExternalApiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_external_api
     *
     * @mbg.generated
     */
    long countByExample(CfgExternalApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_external_api
     *
     * @mbg.generated
     */
    int deleteByExample(CfgExternalApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_external_api
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer externalApiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_external_api
     *
     * @mbg.generated
     */
    int insert(CfgExternalApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_external_api
     *
     * @mbg.generated
     */
    int insertSelective(CfgExternalApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_external_api
     *
     * @mbg.generated
     */
    List<CfgExternalApi> selectByExampleWithRowbounds(CfgExternalApiExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_external_api
     *
     * @mbg.generated
     */
    List<CfgExternalApi> selectByExample(CfgExternalApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_external_api
     *
     * @mbg.generated
     */
    CfgExternalApi selectByPrimaryKey(Integer externalApiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_external_api
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CfgExternalApi record, @Param("example") CfgExternalApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_external_api
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CfgExternalApi record, @Param("example") CfgExternalApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_external_api
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CfgExternalApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cfg_external_api
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CfgExternalApi record);
}