package com.drpeng.ordercenter.persistence.mapper;

import com.drpeng.ordercenter.persistence.entity.OrdBusiParam;
import com.drpeng.ordercenter.persistence.entity.OrdBusiParamExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

@Mapper
public interface OrdBusiParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    int countByExample(OrdBusiParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    int deleteByExample(OrdBusiParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long busiParamId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    int insert(OrdBusiParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    int insertSelective(OrdBusiParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    List<OrdBusiParam> selectByExampleWithRowbounds(OrdBusiParamExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    List<OrdBusiParam> selectByExample(OrdBusiParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    OrdBusiParam selectByPrimaryKey(Long busiParamId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrdBusiParam record, @Param("example") OrdBusiParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrdBusiParam record, @Param("example") OrdBusiParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrdBusiParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrdBusiParam record);
}