package com.drpeng.ordercenter.persistence.mapper;

import com.drpeng.ordercenter.persistence.entity.OrdDetail;
import com.drpeng.ordercenter.persistence.entity.OrdDetailExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;
@Mapper
public interface OrdDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    int countByExample(OrdDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    int deleteByExample(OrdDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    int insert(OrdDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    int insertSelective(OrdDetail record);
    /**
     * This method Batch saving data
     */
    int insertBatch(List<OrdDetail> ordDetails);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    List<OrdDetail> selectByExampleWithRowbounds(OrdDetailExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    List<OrdDetail> selectByExample(OrdDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    OrdDetail selectByPrimaryKey(Long detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrdDetail record, @Param("example") OrdDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrdDetail record, @Param("example") OrdDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrdDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrdDetail record);
}