package com.drpeng.ordercenter.persistence.entity;

public class CfgBusinessProcess {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_business_process.business_process_id
     *
     * @mbg.generated
     */
    private Integer businessProcessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_business_process.business_id
     *
     * @mbg.generated
     */
    private Integer businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_business_process.city_id
     *
     * @mbg.generated
     */
    private String cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_business_process.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_business_process.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_business_process.process_key
     *
     * @mbg.generated
     */
    private String processKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_business_process.business_process_id
     *
     * @return the value of cfg_business_process.business_process_id
     *
     * @mbg.generated
     */
    public Integer getBusinessProcessId() {
        return businessProcessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_business_process.business_process_id
     *
     * @param businessProcessId the value for cfg_business_process.business_process_id
     *
     * @mbg.generated
     */
    public void setBusinessProcessId(Integer businessProcessId) {
        this.businessProcessId = businessProcessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_business_process.business_id
     *
     * @return the value of cfg_business_process.business_id
     *
     * @mbg.generated
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_business_process.business_id
     *
     * @param businessId the value for cfg_business_process.business_id
     *
     * @mbg.generated
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_business_process.city_id
     *
     * @return the value of cfg_business_process.city_id
     *
     * @mbg.generated
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_business_process.city_id
     *
     * @param cityId the value for cfg_business_process.city_id
     *
     * @mbg.generated
     */
    public void setCityId(String cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_business_process.remark
     *
     * @return the value of cfg_business_process.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_business_process.remark
     *
     * @param remark the value for cfg_business_process.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_business_process.status
     *
     * @return the value of cfg_business_process.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_business_process.status
     *
     * @param status the value for cfg_business_process.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_business_process.process_key
     *
     * @return the value of cfg_business_process.process_key
     *
     * @mbg.generated
     */
    public String getProcessKey() {
        return processKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_business_process.process_key
     *
     * @param processKey the value for cfg_business_process.process_key
     *
     * @mbg.generated
     */
    public void setProcessKey(String processKey) {
        this.processKey = processKey;
    }
}