package com.drpeng.ordercenter.persistence.entity;

public class CfgBusinessProcessMapping {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_business_process_mapping.mapping_id
     *
     * @mbg.generated
     */
    private Integer mappingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_business_process_mapping.business_id
     *
     * @mbg.generated
     */
    private Integer businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_business_process_mapping.region_id
     *
     * @mbg.generated
     */
    private String regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_business_process_mapping.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_business_process_mapping.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_business_process_mapping.process_id
     *
     * @mbg.generated
     */
    private String processId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_business_process_mapping.mapping_id
     *
     * @return the value of cfg_business_process_mapping.mapping_id
     *
     * @mbg.generated
     */
    public Integer getMappingId() {
        return mappingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_business_process_mapping.mapping_id
     *
     * @param mappingId the value for cfg_business_process_mapping.mapping_id
     *
     * @mbg.generated
     */
    public void setMappingId(Integer mappingId) {
        this.mappingId = mappingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_business_process_mapping.business_id
     *
     * @return the value of cfg_business_process_mapping.business_id
     *
     * @mbg.generated
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_business_process_mapping.business_id
     *
     * @param businessId the value for cfg_business_process_mapping.business_id
     *
     * @mbg.generated
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_business_process_mapping.region_id
     *
     * @return the value of cfg_business_process_mapping.region_id
     *
     * @mbg.generated
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_business_process_mapping.region_id
     *
     * @param regionId the value for cfg_business_process_mapping.region_id
     *
     * @mbg.generated
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_business_process_mapping.remark
     *
     * @return the value of cfg_business_process_mapping.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_business_process_mapping.remark
     *
     * @param remark the value for cfg_business_process_mapping.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_business_process_mapping.status
     *
     * @return the value of cfg_business_process_mapping.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_business_process_mapping.status
     *
     * @param status the value for cfg_business_process_mapping.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_business_process_mapping.process_id
     *
     * @return the value of cfg_business_process_mapping.process_id
     *
     * @mbg.generated
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_business_process_mapping.process_id
     *
     * @param processId the value for cfg_business_process_mapping.process_id
     *
     * @mbg.generated
     */
    public void setProcessId(String processId) {
        this.processId = processId;
    }
}