package com.drpeng.ordercenter.persistence.entity;

import java.util.Date;

public class CfgBusiness {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_business.business_id
     *
     * @mbggenerated
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_business.business_name
     *
     * @mbggenerated
     */
    private String businessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_business.order_impl_class
     *
     * @mbggenerated
     */
    private String orderImplClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_business.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_business.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_business.business_id
     *
     * @return the value of cfg_business.business_id
     *
     * @mbggenerated
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_business.business_id
     *
     * @param businessId the value for cfg_business.business_id
     *
     * @mbggenerated
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_business.business_name
     *
     * @return the value of cfg_business.business_name
     *
     * @mbggenerated
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_business.business_name
     *
     * @param businessName the value for cfg_business.business_name
     *
     * @mbggenerated
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_business.order_impl_class
     *
     * @return the value of cfg_business.order_impl_class
     *
     * @mbggenerated
     */
    public String getOrderImplClass() {
        return orderImplClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_business.order_impl_class
     *
     * @param orderImplClass the value for cfg_business.order_impl_class
     *
     * @mbggenerated
     */
    public void setOrderImplClass(String orderImplClass) {
        this.orderImplClass = orderImplClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_business.update_time
     *
     * @return the value of cfg_business.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_business.update_time
     *
     * @param updateTime the value for cfg_business.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_business.status
     *
     * @return the value of cfg_business.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_business.status
     *
     * @param status the value for cfg_business.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}