package com.drpeng.ordercenter.persistence.entity;

import java.util.Date;

public class CfgBusinessImpl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_business_impl.business_impl_id
     *
     * @mbggenerated
     */
    private Integer businessImplId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_business_impl.business_id
     *
     * @mbggenerated
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_business_impl.delivery_party
     *
     * @mbggenerated
     */
    private Integer deliveryParty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_business_impl.impl_class
     *
     * @mbggenerated
     */
    private String implClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_business_impl.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_business_impl.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_business_impl.business_impl_id
     *
     * @return the value of cfg_business_impl.business_impl_id
     *
     * @mbggenerated
     */
    public Integer getBusinessImplId() {
        return businessImplId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_business_impl.business_impl_id
     *
     * @param businessImplId the value for cfg_business_impl.business_impl_id
     *
     * @mbggenerated
     */
    public void setBusinessImplId(Integer businessImplId) {
        this.businessImplId = businessImplId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_business_impl.business_id
     *
     * @return the value of cfg_business_impl.business_id
     *
     * @mbggenerated
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_business_impl.business_id
     *
     * @param businessId the value for cfg_business_impl.business_id
     *
     * @mbggenerated
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_business_impl.delivery_party
     *
     * @return the value of cfg_business_impl.delivery_party
     *
     * @mbggenerated
     */
    public Integer getDeliveryParty() {
        return deliveryParty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_business_impl.delivery_party
     *
     * @param deliveryParty the value for cfg_business_impl.delivery_party
     *
     * @mbggenerated
     */
    public void setDeliveryParty(Integer deliveryParty) {
        this.deliveryParty = deliveryParty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_business_impl.impl_class
     *
     * @return the value of cfg_business_impl.impl_class
     *
     * @mbggenerated
     */
    public String getImplClass() {
        return implClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_business_impl.impl_class
     *
     * @param implClass the value for cfg_business_impl.impl_class
     *
     * @mbggenerated
     */
    public void setImplClass(String implClass) {
        this.implClass = implClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_business_impl.update_time
     *
     * @return the value of cfg_business_impl.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_business_impl.update_time
     *
     * @param updateTime the value for cfg_business_impl.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_business_impl.status
     *
     * @return the value of cfg_business_impl.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_business_impl.status
     *
     * @param status the value for cfg_business_impl.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}