package com.drpeng.ordercenter.persistence.entity;

public class CfgExternalApi {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_external_api.external_api_id
     *
     * @mbg.generated
     */
    private Integer externalApiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_external_api.api_code
     *
     * @mbg.generated
     */
    private String apiCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_external_api.api_type
     *
     * @mbg.generated
     */
    private String apiType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_external_api.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_external_api.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_external_api.port
     *
     * @mbg.generated
     */
    private Integer port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_external_api.request_header
     *
     * @mbg.generated
     */
    private String requestHeader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_external_api.timeout
     *
     * @mbg.generated
     */
    private Integer timeout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_external_api.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cfg_external_api.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_external_api.external_api_id
     *
     * @return the value of cfg_external_api.external_api_id
     *
     * @mbg.generated
     */
    public Integer getExternalApiId() {
        return externalApiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_external_api.external_api_id
     *
     * @param externalApiId the value for cfg_external_api.external_api_id
     *
     * @mbg.generated
     */
    public void setExternalApiId(Integer externalApiId) {
        this.externalApiId = externalApiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_external_api.api_code
     *
     * @return the value of cfg_external_api.api_code
     *
     * @mbg.generated
     */
    public String getApiCode() {
        return apiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_external_api.api_code
     *
     * @param apiCode the value for cfg_external_api.api_code
     *
     * @mbg.generated
     */
    public void setApiCode(String apiCode) {
        this.apiCode = apiCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_external_api.api_type
     *
     * @return the value of cfg_external_api.api_type
     *
     * @mbg.generated
     */
    public String getApiType() {
        return apiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_external_api.api_type
     *
     * @param apiType the value for cfg_external_api.api_type
     *
     * @mbg.generated
     */
    public void setApiType(String apiType) {
        this.apiType = apiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_external_api.url
     *
     * @return the value of cfg_external_api.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_external_api.url
     *
     * @param url the value for cfg_external_api.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_external_api.ip
     *
     * @return the value of cfg_external_api.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_external_api.ip
     *
     * @param ip the value for cfg_external_api.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_external_api.port
     *
     * @return the value of cfg_external_api.port
     *
     * @mbg.generated
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_external_api.port
     *
     * @param port the value for cfg_external_api.port
     *
     * @mbg.generated
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_external_api.request_header
     *
     * @return the value of cfg_external_api.request_header
     *
     * @mbg.generated
     */
    public String getRequestHeader() {
        return requestHeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_external_api.request_header
     *
     * @param requestHeader the value for cfg_external_api.request_header
     *
     * @mbg.generated
     */
    public void setRequestHeader(String requestHeader) {
        this.requestHeader = requestHeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_external_api.timeout
     *
     * @return the value of cfg_external_api.timeout
     *
     * @mbg.generated
     */
    public Integer getTimeout() {
        return timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_external_api.timeout
     *
     * @param timeout the value for cfg_external_api.timeout
     *
     * @mbg.generated
     */
    public void setTimeout(Integer timeout) {
        this.timeout = timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_external_api.status
     *
     * @return the value of cfg_external_api.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_external_api.status
     *
     * @param status the value for cfg_external_api.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cfg_external_api.remark
     *
     * @return the value of cfg_external_api.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cfg_external_api.remark
     *
     * @param remark the value for cfg_external_api.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}