package com.drpeng.ordercenter.persistence.entity;

import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

@Component
public class OrdBusiParamExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    public OrdBusiParamExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBusiParamIdIsNull() {
            addCriterion("busi_param_id is null");
            return (Criteria) this;
        }

        public Criteria andBusiParamIdIsNotNull() {
            addCriterion("busi_param_id is not null");
            return (Criteria) this;
        }

        public Criteria andBusiParamIdEqualTo(Long value) {
            addCriterion("busi_param_id =", value, "busiParamId");
            return (Criteria) this;
        }

        public Criteria andBusiParamIdNotEqualTo(Long value) {
            addCriterion("busi_param_id <>", value, "busiParamId");
            return (Criteria) this;
        }

        public Criteria andBusiParamIdGreaterThan(Long value) {
            addCriterion("busi_param_id >", value, "busiParamId");
            return (Criteria) this;
        }

        public Criteria andBusiParamIdGreaterThanOrEqualTo(Long value) {
            addCriterion("busi_param_id >=", value, "busiParamId");
            return (Criteria) this;
        }

        public Criteria andBusiParamIdLessThan(Long value) {
            addCriterion("busi_param_id <", value, "busiParamId");
            return (Criteria) this;
        }

        public Criteria andBusiParamIdLessThanOrEqualTo(Long value) {
            addCriterion("busi_param_id <=", value, "busiParamId");
            return (Criteria) this;
        }

        public Criteria andBusiParamIdIn(List<Long> values) {
            addCriterion("busi_param_id in", values, "busiParamId");
            return (Criteria) this;
        }

        public Criteria andBusiParamIdNotIn(List<Long> values) {
            addCriterion("busi_param_id not in", values, "busiParamId");
            return (Criteria) this;
        }

        public Criteria andBusiParamIdBetween(Long value1, Long value2) {
            addCriterion("busi_param_id between", value1, value2, "busiParamId");
            return (Criteria) this;
        }

        public Criteria andBusiParamIdNotBetween(Long value1, Long value2) {
            addCriterion("busi_param_id not between", value1, value2, "busiParamId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Long value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Long value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Long value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Long value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Long> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Long> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Long value1, Long value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andParamKeyIsNull() {
            addCriterion("param_key is null");
            return (Criteria) this;
        }

        public Criteria andParamKeyIsNotNull() {
            addCriterion("param_key is not null");
            return (Criteria) this;
        }

        public Criteria andParamKeyEqualTo(String value) {
            addCriterion("param_key =", value, "paramKey");
            return (Criteria) this;
        }

        public Criteria andParamKeyNotEqualTo(String value) {
            addCriterion("param_key <>", value, "paramKey");
            return (Criteria) this;
        }

        public Criteria andParamKeyGreaterThan(String value) {
            addCriterion("param_key >", value, "paramKey");
            return (Criteria) this;
        }

        public Criteria andParamKeyGreaterThanOrEqualTo(String value) {
            addCriterion("param_key >=", value, "paramKey");
            return (Criteria) this;
        }

        public Criteria andParamKeyLessThan(String value) {
            addCriterion("param_key <", value, "paramKey");
            return (Criteria) this;
        }

        public Criteria andParamKeyLessThanOrEqualTo(String value) {
            addCriterion("param_key <=", value, "paramKey");
            return (Criteria) this;
        }

        public Criteria andParamKeyLike(String value) {
            addCriterion("param_key like", value, "paramKey");
            return (Criteria) this;
        }

        public Criteria andParamKeyNotLike(String value) {
            addCriterion("param_key not like", value, "paramKey");
            return (Criteria) this;
        }

        public Criteria andParamKeyIn(List<String> values) {
            addCriterion("param_key in", values, "paramKey");
            return (Criteria) this;
        }

        public Criteria andParamKeyNotIn(List<String> values) {
            addCriterion("param_key not in", values, "paramKey");
            return (Criteria) this;
        }

        public Criteria andParamKeyBetween(String value1, String value2) {
            addCriterion("param_key between", value1, value2, "paramKey");
            return (Criteria) this;
        }

        public Criteria andParamKeyNotBetween(String value1, String value2) {
            addCriterion("param_key not between", value1, value2, "paramKey");
            return (Criteria) this;
        }

        public Criteria andParamValueTypeIsNull() {
            addCriterion("param_value_type is null");
            return (Criteria) this;
        }

        public Criteria andParamValueTypeIsNotNull() {
            addCriterion("param_value_type is not null");
            return (Criteria) this;
        }

        public Criteria andParamValueTypeEqualTo(Integer value) {
            addCriterion("param_value_type =", value, "paramValueType");
            return (Criteria) this;
        }

        public Criteria andParamValueTypeNotEqualTo(Integer value) {
            addCriterion("param_value_type <>", value, "paramValueType");
            return (Criteria) this;
        }

        public Criteria andParamValueTypeGreaterThan(Integer value) {
            addCriterion("param_value_type >", value, "paramValueType");
            return (Criteria) this;
        }

        public Criteria andParamValueTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("param_value_type >=", value, "paramValueType");
            return (Criteria) this;
        }

        public Criteria andParamValueTypeLessThan(Integer value) {
            addCriterion("param_value_type <", value, "paramValueType");
            return (Criteria) this;
        }

        public Criteria andParamValueTypeLessThanOrEqualTo(Integer value) {
            addCriterion("param_value_type <=", value, "paramValueType");
            return (Criteria) this;
        }

        public Criteria andParamValueTypeIn(List<Integer> values) {
            addCriterion("param_value_type in", values, "paramValueType");
            return (Criteria) this;
        }

        public Criteria andParamValueTypeNotIn(List<Integer> values) {
            addCriterion("param_value_type not in", values, "paramValueType");
            return (Criteria) this;
        }

        public Criteria andParamValueTypeBetween(Integer value1, Integer value2) {
            addCriterion("param_value_type between", value1, value2, "paramValueType");
            return (Criteria) this;
        }

        public Criteria andParamValueTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("param_value_type not between", value1, value2, "paramValueType");
            return (Criteria) this;
        }

        public Criteria andParamValueIsNull() {
            addCriterion("param_value is null");
            return (Criteria) this;
        }

        public Criteria andParamValueIsNotNull() {
            addCriterion("param_value is not null");
            return (Criteria) this;
        }

        public Criteria andParamValueEqualTo(String value) {
            addCriterion("param_value =", value, "paramValue");
            return (Criteria) this;
        }

        public Criteria andParamValueNotEqualTo(String value) {
            addCriterion("param_value <>", value, "paramValue");
            return (Criteria) this;
        }

        public Criteria andParamValueGreaterThan(String value) {
            addCriterion("param_value >", value, "paramValue");
            return (Criteria) this;
        }

        public Criteria andParamValueGreaterThanOrEqualTo(String value) {
            addCriterion("param_value >=", value, "paramValue");
            return (Criteria) this;
        }

        public Criteria andParamValueLessThan(String value) {
            addCriterion("param_value <", value, "paramValue");
            return (Criteria) this;
        }

        public Criteria andParamValueLessThanOrEqualTo(String value) {
            addCriterion("param_value <=", value, "paramValue");
            return (Criteria) this;
        }

        public Criteria andParamValueLike(String value) {
            addCriterion("param_value like", value, "paramValue");
            return (Criteria) this;
        }

        public Criteria andParamValueNotLike(String value) {
            addCriterion("param_value not like", value, "paramValue");
            return (Criteria) this;
        }

        public Criteria andParamValueIn(List<String> values) {
            addCriterion("param_value in", values, "paramValue");
            return (Criteria) this;
        }

        public Criteria andParamValueNotIn(List<String> values) {
            addCriterion("param_value not in", values, "paramValue");
            return (Criteria) this;
        }

        public Criteria andParamValueBetween(String value1, String value2) {
            addCriterion("param_value between", value1, value2, "paramValue");
            return (Criteria) this;
        }

        public Criteria andParamValueNotBetween(String value1, String value2) {
            addCriterion("param_value not between", value1, value2, "paramValue");
            return (Criteria) this;
        }

        public Criteria andParentBusiParamIdIsNull() {
            addCriterion("parent_busi_param_id is null");
            return (Criteria) this;
        }

        public Criteria andParentBusiParamIdIsNotNull() {
            addCriterion("parent_busi_param_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentBusiParamIdEqualTo(Long value) {
            addCriterion("parent_busi_param_id =", value, "parentBusiParamId");
            return (Criteria) this;
        }

        public Criteria andParentBusiParamIdNotEqualTo(Long value) {
            addCriterion("parent_busi_param_id <>", value, "parentBusiParamId");
            return (Criteria) this;
        }

        public Criteria andParentBusiParamIdGreaterThan(Long value) {
            addCriterion("parent_busi_param_id >", value, "parentBusiParamId");
            return (Criteria) this;
        }

        public Criteria andParentBusiParamIdGreaterThanOrEqualTo(Long value) {
            addCriterion("parent_busi_param_id >=", value, "parentBusiParamId");
            return (Criteria) this;
        }

        public Criteria andParentBusiParamIdLessThan(Long value) {
            addCriterion("parent_busi_param_id <", value, "parentBusiParamId");
            return (Criteria) this;
        }

        public Criteria andParentBusiParamIdLessThanOrEqualTo(Long value) {
            addCriterion("parent_busi_param_id <=", value, "parentBusiParamId");
            return (Criteria) this;
        }

        public Criteria andParentBusiParamIdIn(List<Long> values) {
            addCriterion("parent_busi_param_id in", values, "parentBusiParamId");
            return (Criteria) this;
        }

        public Criteria andParentBusiParamIdNotIn(List<Long> values) {
            addCriterion("parent_busi_param_id not in", values, "parentBusiParamId");
            return (Criteria) this;
        }

        public Criteria andParentBusiParamIdBetween(Long value1, Long value2) {
            addCriterion("parent_busi_param_id between", value1, value2, "parentBusiParamId");
            return (Criteria) this;
        }

        public Criteria andParentBusiParamIdNotBetween(Long value1, Long value2) {
            addCriterion("parent_busi_param_id not between", value1, value2, "parentBusiParamId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ord_busi_param
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ord_busi_param
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}