package com.drpeng.ordercenter.persistence.entity;

public class OrdBusiParam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ord_busi_param.busi_param_id
     *
     * @mbggenerated
     */
    private Long busiParamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ord_busi_param.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ord_busi_param.param_key
     *
     * @mbggenerated
     */
    private String paramKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ord_busi_param.param_value_type
     *
     * @mbggenerated
     */
    private Integer paramValueType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ord_busi_param.param_value
     *
     * @mbggenerated
     */
    private String paramValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ord_busi_param.parent_busi_param_id
     *
     * @mbggenerated
     */
    private Long parentBusiParamId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ord_busi_param.busi_param_id
     *
     * @return the value of ord_busi_param.busi_param_id
     *
     * @mbggenerated
     */
    public Long getBusiParamId() {
        return busiParamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ord_busi_param.busi_param_id
     *
     * @param busiParamId the value for ord_busi_param.busi_param_id
     *
     * @mbggenerated
     */
    public void setBusiParamId(Long busiParamId) {
        this.busiParamId = busiParamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ord_busi_param.order_id
     *
     * @return the value of ord_busi_param.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ord_busi_param.order_id
     *
     * @param orderId the value for ord_busi_param.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ord_busi_param.param_key
     *
     * @return the value of ord_busi_param.param_key
     *
     * @mbggenerated
     */
    public String getParamKey() {
        return paramKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ord_busi_param.param_key
     *
     * @param paramKey the value for ord_busi_param.param_key
     *
     * @mbggenerated
     */
    public void setParamKey(String paramKey) {
        this.paramKey = paramKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ord_busi_param.param_value_type
     *
     * @return the value of ord_busi_param.param_value_type
     *
     * @mbggenerated
     */
    public Integer getParamValueType() {
        return paramValueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ord_busi_param.param_value_type
     *
     * @param paramValueType the value for ord_busi_param.param_value_type
     *
     * @mbggenerated
     */
    public void setParamValueType(Integer paramValueType) {
        this.paramValueType = paramValueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ord_busi_param.param_value
     *
     * @return the value of ord_busi_param.param_value
     *
     * @mbggenerated
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ord_busi_param.param_value
     *
     * @param paramValue the value for ord_busi_param.param_value
     *
     * @mbggenerated
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ord_busi_param.parent_busi_param_id
     *
     * @return the value of ord_busi_param.parent_busi_param_id
     *
     * @mbggenerated
     */
    public Long getParentBusiParamId() {
        return parentBusiParamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ord_busi_param.parent_busi_param_id
     *
     * @param parentBusiParamId the value for ord_busi_param.parent_busi_param_id
     *
     * @mbggenerated
     */
    public void setParentBusiParamId(Long parentBusiParamId) {
        this.parentBusiParamId = parentBusiParamId;
    }
}