package com.drpeng.ordercenter.persistence.entity;

import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;
@Component
public class OrdDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    public OrdDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDetailIdIsNull() {
            addCriterion("detail_id is null");
            return (Criteria) this;
        }

        public Criteria andDetailIdIsNotNull() {
            addCriterion("detail_id is not null");
            return (Criteria) this;
        }

        public Criteria andDetailIdEqualTo(Long value) {
            addCriterion("detail_id =", value, "detailId");
            return (Criteria) this;
        }

        public Criteria andDetailIdNotEqualTo(Long value) {
            addCriterion("detail_id <>", value, "detailId");
            return (Criteria) this;
        }

        public Criteria andDetailIdGreaterThan(Long value) {
            addCriterion("detail_id >", value, "detailId");
            return (Criteria) this;
        }

        public Criteria andDetailIdGreaterThanOrEqualTo(Long value) {
            addCriterion("detail_id >=", value, "detailId");
            return (Criteria) this;
        }

        public Criteria andDetailIdLessThan(Long value) {
            addCriterion("detail_id <", value, "detailId");
            return (Criteria) this;
        }

        public Criteria andDetailIdLessThanOrEqualTo(Long value) {
            addCriterion("detail_id <=", value, "detailId");
            return (Criteria) this;
        }

        public Criteria andDetailIdIn(List<Long> values) {
            addCriterion("detail_id in", values, "detailId");
            return (Criteria) this;
        }

        public Criteria andDetailIdNotIn(List<Long> values) {
            addCriterion("detail_id not in", values, "detailId");
            return (Criteria) this;
        }

        public Criteria andDetailIdBetween(Long value1, Long value2) {
            addCriterion("detail_id between", value1, value2, "detailId");
            return (Criteria) this;
        }

        public Criteria andDetailIdNotBetween(Long value1, Long value2) {
            addCriterion("detail_id not between", value1, value2, "detailId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Long value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Long value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Long value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Long value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Long> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Long> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Long value1, Long value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andDetailKeyIsNull() {
            addCriterion("detail_key is null");
            return (Criteria) this;
        }

        public Criteria andDetailKeyIsNotNull() {
            addCriterion("detail_key is not null");
            return (Criteria) this;
        }

        public Criteria andDetailKeyEqualTo(String value) {
            addCriterion("detail_key =", value, "detailKey");
            return (Criteria) this;
        }

        public Criteria andDetailKeyNotEqualTo(String value) {
            addCriterion("detail_key <>", value, "detailKey");
            return (Criteria) this;
        }

        public Criteria andDetailKeyGreaterThan(String value) {
            addCriterion("detail_key >", value, "detailKey");
            return (Criteria) this;
        }

        public Criteria andDetailKeyGreaterThanOrEqualTo(String value) {
            addCriterion("detail_key >=", value, "detailKey");
            return (Criteria) this;
        }

        public Criteria andDetailKeyLessThan(String value) {
            addCriterion("detail_key <", value, "detailKey");
            return (Criteria) this;
        }

        public Criteria andDetailKeyLessThanOrEqualTo(String value) {
            addCriterion("detail_key <=", value, "detailKey");
            return (Criteria) this;
        }

        public Criteria andDetailKeyLike(String value) {
            addCriterion("detail_key like", value, "detailKey");
            return (Criteria) this;
        }

        public Criteria andDetailKeyNotLike(String value) {
            addCriterion("detail_key not like", value, "detailKey");
            return (Criteria) this;
        }

        public Criteria andDetailKeyIn(List<String> values) {
            addCriterion("detail_key in", values, "detailKey");
            return (Criteria) this;
        }

        public Criteria andDetailKeyNotIn(List<String> values) {
            addCriterion("detail_key not in", values, "detailKey");
            return (Criteria) this;
        }

        public Criteria andDetailKeyBetween(String value1, String value2) {
            addCriterion("detail_key between", value1, value2, "detailKey");
            return (Criteria) this;
        }

        public Criteria andDetailKeyNotBetween(String value1, String value2) {
            addCriterion("detail_key not between", value1, value2, "detailKey");
            return (Criteria) this;
        }

        public Criteria andDetailValueTypeIsNull() {
            addCriterion("detail_value_type is null");
            return (Criteria) this;
        }

        public Criteria andDetailValueTypeIsNotNull() {
            addCriterion("detail_value_type is not null");
            return (Criteria) this;
        }

        public Criteria andDetailValueTypeEqualTo(Integer value) {
            addCriterion("detail_value_type =", value, "detailValueType");
            return (Criteria) this;
        }

        public Criteria andDetailValueTypeNotEqualTo(Integer value) {
            addCriterion("detail_value_type <>", value, "detailValueType");
            return (Criteria) this;
        }

        public Criteria andDetailValueTypeGreaterThan(Integer value) {
            addCriterion("detail_value_type >", value, "detailValueType");
            return (Criteria) this;
        }

        public Criteria andDetailValueTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("detail_value_type >=", value, "detailValueType");
            return (Criteria) this;
        }

        public Criteria andDetailValueTypeLessThan(Integer value) {
            addCriterion("detail_value_type <", value, "detailValueType");
            return (Criteria) this;
        }

        public Criteria andDetailValueTypeLessThanOrEqualTo(Integer value) {
            addCriterion("detail_value_type <=", value, "detailValueType");
            return (Criteria) this;
        }

        public Criteria andDetailValueTypeIn(List<Integer> values) {
            addCriterion("detail_value_type in", values, "detailValueType");
            return (Criteria) this;
        }

        public Criteria andDetailValueTypeNotIn(List<Integer> values) {
            addCriterion("detail_value_type not in", values, "detailValueType");
            return (Criteria) this;
        }

        public Criteria andDetailValueTypeBetween(Integer value1, Integer value2) {
            addCriterion("detail_value_type between", value1, value2, "detailValueType");
            return (Criteria) this;
        }

        public Criteria andDetailValueTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("detail_value_type not between", value1, value2, "detailValueType");
            return (Criteria) this;
        }

        public Criteria andDetailValueIsNull() {
            addCriterion("detail_value is null");
            return (Criteria) this;
        }

        public Criteria andDetailValueIsNotNull() {
            addCriterion("detail_value is not null");
            return (Criteria) this;
        }

        public Criteria andDetailValueEqualTo(String value) {
            addCriterion("detail_value =", value, "detailValue");
            return (Criteria) this;
        }

        public Criteria andDetailValueNotEqualTo(String value) {
            addCriterion("detail_value <>", value, "detailValue");
            return (Criteria) this;
        }

        public Criteria andDetailValueGreaterThan(String value) {
            addCriterion("detail_value >", value, "detailValue");
            return (Criteria) this;
        }

        public Criteria andDetailValueGreaterThanOrEqualTo(String value) {
            addCriterion("detail_value >=", value, "detailValue");
            return (Criteria) this;
        }

        public Criteria andDetailValueLessThan(String value) {
            addCriterion("detail_value <", value, "detailValue");
            return (Criteria) this;
        }

        public Criteria andDetailValueLessThanOrEqualTo(String value) {
            addCriterion("detail_value <=", value, "detailValue");
            return (Criteria) this;
        }

        public Criteria andDetailValueLike(String value) {
            addCriterion("detail_value like", value, "detailValue");
            return (Criteria) this;
        }

        public Criteria andDetailValueNotLike(String value) {
            addCriterion("detail_value not like", value, "detailValue");
            return (Criteria) this;
        }

        public Criteria andDetailValueIn(List<String> values) {
            addCriterion("detail_value in", values, "detailValue");
            return (Criteria) this;
        }

        public Criteria andDetailValueNotIn(List<String> values) {
            addCriterion("detail_value not in", values, "detailValue");
            return (Criteria) this;
        }

        public Criteria andDetailValueBetween(String value1, String value2) {
            addCriterion("detail_value between", value1, value2, "detailValue");
            return (Criteria) this;
        }

        public Criteria andDetailValueNotBetween(String value1, String value2) {
            addCriterion("detail_value not between", value1, value2, "detailValue");
            return (Criteria) this;
        }

        public Criteria andParentDetailIdIsNull() {
            addCriterion("parent_detail_id is null");
            return (Criteria) this;
        }

        public Criteria andParentDetailIdIsNotNull() {
            addCriterion("parent_detail_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentDetailIdEqualTo(Long value) {
            addCriterion("parent_detail_id =", value, "parentDetailId");
            return (Criteria) this;
        }

        public Criteria andParentDetailIdNotEqualTo(Long value) {
            addCriterion("parent_detail_id <>", value, "parentDetailId");
            return (Criteria) this;
        }

        public Criteria andParentDetailIdGreaterThan(Long value) {
            addCriterion("parent_detail_id >", value, "parentDetailId");
            return (Criteria) this;
        }

        public Criteria andParentDetailIdGreaterThanOrEqualTo(Long value) {
            addCriterion("parent_detail_id >=", value, "parentDetailId");
            return (Criteria) this;
        }

        public Criteria andParentDetailIdLessThan(Long value) {
            addCriterion("parent_detail_id <", value, "parentDetailId");
            return (Criteria) this;
        }

        public Criteria andParentDetailIdLessThanOrEqualTo(Long value) {
            addCriterion("parent_detail_id <=", value, "parentDetailId");
            return (Criteria) this;
        }

        public Criteria andParentDetailIdIn(List<Long> values) {
            addCriterion("parent_detail_id in", values, "parentDetailId");
            return (Criteria) this;
        }

        public Criteria andParentDetailIdNotIn(List<Long> values) {
            addCriterion("parent_detail_id not in", values, "parentDetailId");
            return (Criteria) this;
        }

        public Criteria andParentDetailIdBetween(Long value1, Long value2) {
            addCriterion("parent_detail_id between", value1, value2, "parentDetailId");
            return (Criteria) this;
        }

        public Criteria andParentDetailIdNotBetween(Long value1, Long value2) {
            addCriterion("parent_detail_id not between", value1, value2, "parentDetailId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ord_detail
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ord_detail
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}