package com.drpeng.ordercenter.persistence.entity;

public class OrdDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ord_detail.detail_id
     *
     * @mbggenerated
     */
    private Long detailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ord_detail.order_id
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ord_detail.detail_key
     *
     * @mbggenerated
     */
    private String detailKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ord_detail.detail_value_type
     *
     * @mbggenerated
     */
    private Integer detailValueType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ord_detail.detail_value
     *
     * @mbggenerated
     */
    private String detailValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ord_detail.parent_detail_id
     *
     * @mbggenerated
     */
    private Long parentDetailId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ord_detail.detail_id
     *
     * @return the value of ord_detail.detail_id
     *
     * @mbggenerated
     */
    public Long getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ord_detail.detail_id
     *
     * @param detailId the value for ord_detail.detail_id
     *
     * @mbggenerated
     */
    public void setDetailId(Long detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ord_detail.order_id
     *
     * @return the value of ord_detail.order_id
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ord_detail.order_id
     *
     * @param orderId the value for ord_detail.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ord_detail.detail_key
     *
     * @return the value of ord_detail.detail_key
     *
     * @mbggenerated
     */
    public String getDetailKey() {
        return detailKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ord_detail.detail_key
     *
     * @param detailKey the value for ord_detail.detail_key
     *
     * @mbggenerated
     */
    public void setDetailKey(String detailKey) {
        this.detailKey = detailKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ord_detail.detail_value_type
     *
     * @return the value of ord_detail.detail_value_type
     *
     * @mbggenerated
     */
    public Integer getDetailValueType() {
        return detailValueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ord_detail.detail_value_type
     *
     * @param detailValueType the value for ord_detail.detail_value_type
     *
     * @mbggenerated
     */
    public void setDetailValueType(Integer detailValueType) {
        this.detailValueType = detailValueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ord_detail.detail_value
     *
     * @return the value of ord_detail.detail_value
     *
     * @mbggenerated
     */
    public String getDetailValue() {
        return detailValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ord_detail.detail_value
     *
     * @param detailValue the value for ord_detail.detail_value
     *
     * @mbggenerated
     */
    public void setDetailValue(String detailValue) {
        this.detailValue = detailValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ord_detail.parent_detail_id
     *
     * @return the value of ord_detail.parent_detail_id
     *
     * @mbggenerated
     */
    public Long getParentDetailId() {
        return parentDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ord_detail.parent_detail_id
     *
     * @param parentDetailId the value for ord_detail.parent_detail_id
     *
     * @mbggenerated
     */
    public void setParentDetailId(Long parentDetailId) {
        this.parentDetailId = parentDetailId;
    }
}